### ISSUE TITLE
Soundex W and H

### ISSUE THREAD

**Issue by mpkorstanje** [Simmetrics/libsimmetrics#5]
I don't think this is correct. Going by the wikipedia article on soundex a character is also considered repeated when seperated by a W or H.

```
    while (incount < ((int) strlen(str)) && count < ((int) strlen(out))) {

        mapped = get_mapping_code(str, incount++);

        if (mapped != 0) {

            if (mapped != '0' && mapped != last) {

                out[count++] = mapped;

            }

            last = mapped;

        }

    }
```

For contrast my java code:

```
        StringBuilder builder = new StringBuilder(length);
        builder.append(wordStr.charAt(0));

        char previousCharacter = wordStr.charAt(0);
        for (int i = 1; i < wordStr.length() && builder.length() < length; i++) {
            char character = wordStr.charAt(i);
            char characterCode = CHAR_CODE[character - OFFSET];
            char previousCharacterCode = CHAR_CODE[previousCharacter - OFFSET];

            if (
            // Don't add ignored codes
            characterCode != IGNORE &&
            // Don't add repeated codes
                    characterCode != previousCharacterCode) {
                builder.append(characterCode);

            }

            // A code is also considered repeated when separated by a W or H.
            if (character != 'W' && character != 'H') {
                previousCharacter = character;
            }
        }

```

And some test case

```
    /**
     * Tests references from <a href="http://en.wikipedia.org/wiki/Soundex"
     * >Wikipedia - Soundex</a>
     */
    @Test
    public void testWikipediaExamples() {

        Simplifier simplifier = new SoundexSimplifier(4);

        assertEquals("R163", simplifier.simplify("Robert"));
        assertEquals("R163", simplifier.simplify("Rupert"));
        assertEquals("R150", simplifier.simplify("Rubin"));

        assertEquals("A261", simplifier.simplify("Ashcraft"));
        assertEquals("A261", simplifier.simplify("Ashcroft"));

        assertEquals("T522", simplifier.simplify("Tymczak"));
        assertEquals("P236", simplifier.simplify("Pfister"));
    }
```

**Comment by jokillsya** [comment]
That's handled in the get_mapping_code function...

On Sat, Feb 21, 2015 at 2:28 AM, mpkorstanje notifications@github.com
wrote:

> I don't think this is correct. Going by the wikipedia article on soundex a
> character is also considered repeated when seperated by a W or H.
> 
> ```
> while (incount < ((int) strlen(str)) && count < ((int) strlen(out))) {
> 
>     mapped = get_mapping_code(str, incount++);
> 
>     if (mapped != 0) {
> 
>         if (mapped != '0' && mapped != last) {
> 
>             out[count++] = mapped;
> 
>         }
> 
>         last = mapped;
> 
>     }
> 
> }
> ```
> 
> For contrast my java code:
> 
> ```
>     StringBuilder builder = new StringBuilder(length);
>     builder.append(wordStr.charAt(0));
> 
>     char previousCharacter = wordStr.charAt(0);
>     for (int i = 1; i < wordStr.length() && builder.length() < length; i++) {
>         char character = wordStr.charAt(i);
>         char characterCode = CHAR_CODE[character - OFFSET];
>         char previousCharacterCode = CHAR_CODE[previousCharacter - OFFSET];
> 
>         if (
>         // Don't add ignored codes
>         characterCode != IGNORE &&
>         // Don't add repeated codes
>                 characterCode != previousCharacterCode) {
>             builder.append(characterCode);
> 
>         }
> 
>         // A code is also considered repeated when separated by a W or H.
>         if (character != 'W' && character != 'H') {
>             previousCharacter = character;
>         }
>     }
> ```
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Simmetrics/libsimmetrics/issues/5.

## 

Best Regards

Johnathan Botha

**Comment by jokillsya** [comment]
static char get_mapping_code(const char *str, const int index) {
char m_chr = map(str[index]);
if (m_chr == '\0') {
return ('\0');
}
if (index > 1 && m_chr != '0') {
char hw_chr = str[index - 1];
if ('H' == hw_chr || 'W' == hw_chr) {
char pre_hw_char = str[index - 2]; char f_code = map(pre_hw_char);
if ((f_code == m_chr) || ('H' == pre_hw_char) || ('W' == pre_hw_char)) {
m_chr = 0;
}
}
}
return (m_chr);
}

**Comment by mpkorstanje** [comment]
Cheers. Makes sense.
